# Generated by Django 3.1.6 on 2021-04-03 22:56

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_superuser', models.BooleanField(default=False, help_text='Tiene todo los permisos sin asignárselo ', verbose_name='super usuario')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='account', verbose_name='perfil')),
                ('user_type', models.CharField(choices=[('OPTIC', 'Optic'), ('EMPLOYEE', 'Employee')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='OpticUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_name', models.CharField(max_length=100, verbose_name='Nombre en la prescripcion')),
                ('optic_name', models.CharField(max_length=50, verbose_name='Nombre de la optica')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpticUser',
                'verbose_name_plural': 'OpticUsers',
            },
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico')),
                ('prescription_name', models.CharField(max_length=100, verbose_name='Nombre en la prescripcion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('other_phone', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('optic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.opticuser')),
            ],
            options={
                'verbose_name': 'EmployeeUser',
                'verbose_name_plural': 'EmployeeUsers',
            },
        ),
    ]
