# Generated by Django 3.1.6 on 2021-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='codigo de verificacion'),
        ),
        migrations.AddField(
            model_name='account',
            name='verify_email',
            field=models.BooleanField(default=False, verbose_name='email verificado'),
        ),
    ]
