# Generated by Django 3.1.6 on 2021-04-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210410_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticuser',
            name='optic_name',
            field=models.CharField(max_length=30, verbose_name='Nombre de la optica'),
        ),
    ]
