# Generated by Django 3.1.6 on 2021-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210414_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero de contacto'),
        ),
    ]
