# Generated by Django 3.1.6 on 2021-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='dip_or_dnp',
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_dip',
            field=models.BooleanField(default=True, verbose_name='Dip o Dnp'),
        ),
    ]
