# Generated by Django 3.1.6 on 2021-04-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210419_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeuser',
            options={'permissions': [('view_admin', 'Puede ver la administración')], 'verbose_name': 'EmployeeUser', 'verbose_name_plural': 'EmployeeUsers'},
        ),
    ]
