# Generated by Django 3.1.6 on 2021-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210425_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeuser',
            options={'verbose_name': 'EmployeeUser', 'verbose_name_plural': 'EmployeeUsers'},
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='other_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular 2'),
        ),
    ]
