# Generated by Django 3.1.6 on 2021-04-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210425_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('OPTIC', 'OPTICA'), ('EMPLOYEE', 'EMPLEADO')], max_length=10),
        ),
    ]
