# Generated by Django 3.1.6 on 2021-04-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210426_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='verification_code',
        ),
    ]
