# Generated by Django 3.1.5 on 2021-01-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, verbose_name='Dni')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(verbose_name='Observacion')),
                ('spherical_right', models.FloatField(null=True, verbose_name='Esferico derecho')),
                ('spherical_left', models.FloatField(null=True, verbose_name='Esferico izquierdo')),
                ('Axis_right', models.FloatField(null=True, verbose_name='Eje derecho')),
                ('Axis_left', models.FloatField(null=True, verbose_name='Eje izquierdo')),
                ('Cylinder_right', models.FloatField(null=True, verbose_name='Cilindro derecho')),
                ('Cylinder_left', models.FloatField(null=True, verbose_name='Cilindro izquierdo')),
                ('Price', models.FloatField(null=True, verbose_name='Precio')),
                ('Laboratory_name', models.CharField(max_length=50, null=True, verbose_name='Laboratorio')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidas.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
    ]
