# Generated by Django 3.1.6 on 2021-04-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0002_auto_20210403_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='crystal_name',
            field=models.CharField(max_length=70, verbose_name='Nombre Luna'),
        ),
    ]
