# Generated by Django 3.1.5 on 2021-01-30 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0003_auto_20210130_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_spherical_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Esferico derecho Lejos')),
                ('far_cylinder_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cilindro derecho Lejos')),
                ('far_axis_right', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180, 'El eje solo permite valores entre 0 y 180')], verbose_name='Eje derecho Lejos')),
                ('far_spherical_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Esferico izquierdo Lejos')),
                ('far_cylinder_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cilindro izquierdo Lejos')),
                ('far_axis_left', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180, 'El eje solo permite valores entre 0 y 180')], verbose_name='Eje izquierdo Lejos')),
                ('near_spherical_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Esferico derecho Cerca')),
                ('near_cylinder_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cilindro derecho Cerca')),
                ('near_axis_right', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180, 'El eje solo permite valores entre 0 y 180')], verbose_name='Eje derecho Cerca')),
                ('near_spherical_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Esferico izquierdo Cerca')),
                ('near_cylinder_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cilindro izquierdo Cerca')),
                ('near_axis_left', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180, 'El eje solo permite valores entre 0 y 180')], verbose_name='Eje izquierdo Cerca')),
                ('observation', models.TextField(blank=True, verbose_name='Observacion')),
                ('dip', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Distancia interpupilar')),
                ('add', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Adicion')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medidas.laboratory', verbose_name='Laboratorio')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidas.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
