# Generated by Django 3.1.5 on 2021-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0004_auto_20210130_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ADD'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dip',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='DIP'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_cylinder_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro izquierdo Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_cylinder_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro derecho Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_spherical_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esferico izquierdo Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_spherical_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esferico derecho Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_cylinder_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro izquierdo Cerca'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_cylinder_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro derecho Cerca'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_spherical_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esferico izquierdo Cerca'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_spherical_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esferico derecho Cerca'),
        ),
    ]
