# Generated by Django 3.1.6 on 2021-04-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0005_auto_20210404_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medidas.crystalmaterial', verbose_name='Material'),
        ),
    ]
