# Generated by Django 3.1.5 on 2021-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0005_auto_20210130_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_cylinder_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cil. izquierdo Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_cylinder_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cil. derecho Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_spherical_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esf. izquierdo Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='far_spherical_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esf. derecho Lejos'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_cylinder_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cil. izquierdo Cerca'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_cylinder_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cil. derecho Cerca'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_spherical_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esf. izquierdo Cerca'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='near_spherical_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Esf. derecho Cerca'),
        ),
    ]
