# Generated by Django 3.1.5 on 2021-01-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0006_auto_20210130_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='fecha',
            new_name='date',
        ),
    ]
