# Generated by Django 3.1.6 on 2021-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0009_auto_20210413_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='time',
        ),
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dni'),
        ),
    ]
