# Generated by Django 3.1.6 on 2021-04-14 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0010_auto_20210414_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dni o Pasaporte'),
        ),
    ]
