# Generated by Django 3.1.6 on 2021-04-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0011_auto_20210414_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(blank=True, choices=[('MONOFOCAL', 'Monofocal'), ('BIFOCAL', 'Bifocal'), ('OCCUPATIONAL', 'Ocupacional'), ('PROGRESSIVE', 'Progressivo')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
