# Generated by Django 3.1.6 on 2021-02-16 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0013_auto_20210215_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
