# Generated by Django 3.1.6 on 2021-04-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0014_auto_20210415_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='phone',
            field=models.CharField(blank=True, max_length=23, verbose_name='Telefono'),
        ),
    ]
