# Generated by Django 3.1.6 on 2021-04-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0016_prescription_is_dip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='is_dip',
            field=models.BooleanField(verbose_name='Dip o Dnp'),
        ),
    ]
