# Generated by Django 3.1.6 on 2021-04-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0017_auto_20210419_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medidas.patient', verbose_name='Paciente'),
        ),
    ]
