# Generated by Django 3.1.6 on 2021-04-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210426_0249'),
        ('medidas', '0018_auto_20210425_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=40, verbose_name='Laboratorio')),
                ('direction', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=23, verbose_name='Telefono')),
                ('optic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.opticuser', verbose_name='Optica')),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratorys',
            },
        ),
    ]
