# Generated by Django 3.1.6 on 2021-05-04 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0021_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='crystals_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, 'No se permite el valor ingresado')], verbose_name='Costo de las lunas'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='crystals_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, 'No se permite el valor ingresado')], verbose_name='Precio de venta de las lunas'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frame_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, 'No se permite el valor ingresado')], verbose_name='Precio de venta de la montura'),
        ),
    ]
